### PR TITLE
Make coversion of text to optional, keeping defualt true to make sure…

### PR DESCRIPTION
**Pull request by ianlongden**
… previous uses of the mehod with no new parameters still works. This may need some TLC at some point as it is getting a little messy but should be okay for now.

### CODE REVIEW

**Review by christabone — DISMISSED** [review]

**Comment by christabone** [comment]
Since it's a critical function, I think @gildossantos should have a quick look too, if that's OK.

**Comment by ianlongden** [comment]
Sure, no problem, I shall await  Gil's approval before merging (If approved of course).

**Comment by ianlongden** [comment]
Actually I need to remove the warning.

**Comment by ianlongden** [comment]
Done, I will await @gildossantos review.

**Review by christabone — APPROVED** [review]

**Pull request merged**
