### PR TITLE
Strings

### PR DESCRIPTION
**Pull request by ianlongden**
Got up to FeatureCvtermDbxref. Might be good to get a review.
Not sure if i reporting too much (going down too many levels).
Added a test file so you can see the output, to run do:-

python test_chado_object_class_output.py -c chado.cfg

### CODE REVIEW

**Comment by christabone** [comment]
OK if I put this off until tomorrow?

**Comment by ianlongden** [comment]
Sure no problem. Its seems to be failing anyway!!

**Comment by ianlongden** [comment]
Okay i had a file which started 'test_' so it thought it was a test. More of an example as it needs a cfg file.

**Comment by ianlongden** [comment]
So it looks good for things like feature and dbxref:-
Feature id=53257035: uniquename:'JM973022' name:'JM973022' obsolete:False
	type:(Cvterm id=218: name:'transposable_element_flanking_region' cv:(Cv id=6: SO))

Dbxrefprop id=276693: value:'' rank:'0'
	dbxref:(Dbxref id=10804154: acc:'10010-AA142e[1]' Db:(Db id=376: name:'apodroso'))
	type:(Cvterm id=98086: name:'linkout' cv:(Cv id=39: dbxrefprop type))

But for more complicated tables i.e.  CellLineLibraryprop:-
CellLineLibraryprop id=75: value:None rank:0
	Library:(CellLineLibrary id=155:
	cell line:(CellLine id=13: uniquename:'FBtc0000999' name:'Schneider's-line-2' organism:(Organism id=1: abbr:'Dmel' genus:'Drosophila' species:'melanogaster'))
	library:(Library id=1174: uniquename:FBlc0000893 name:BS_SD_cDNA obsolete:False
	org:(Organism id=1: abbr:'Dmel' genus:'Drosophila' species:'melanogaster')
	type:(Cvterm id=132463: name:'biosample' cv:(Cv id=20: FlyBase miscellaneous CV)))
	pub:(Pub id=150347: uniquename:FBrf0127297 title:'A Drosophila complementary DNA resource.' miniref:'Rubin et al., 2000, Science 287(5461): 2222--2224' type:(Cvterm id=57084: name:'review' cv:(Cv id=1: pub type)) obsolete:False))

It gets a bit more complicated.

I probably think this is okay as it is for developers and we should be able to work all this out.

There is a caveat here wrt speed. This should be used in debugging and not printing info to the user or log files. Why? Becouse the print will do some sql queries in the background to follow the relationships.
i.e. for a feature, the cvterm is looked up and then the cv.
So for logging if you want info on the feature it will be quicker to print feature.uniquename or something.

I think the pros outway the cons. It could be changed to not do this but i like having ALL the info saves me having to do lookups later for more complex objects.

**Comment by ianlongden** [comment]
I will crack on with doing the others for now, so no need to merge until i have finished, but please look if you want to add any feedback.

**Comment by ianlongden** [comment]
Okay done a lot of this but i will do the rest when needed, so happy for it to be reviewed and merged for now.

**Comment by gildossantos** [comment]
Shall I merge or you wanna wait?

**Comment by ianlongden** [comment]
I'll merge it. It has to be better than what is there presently. I can make
changes if needed based on if Chris has anything to add. Thanks.

**Pull request merged**
